title: numberMumbler.com
description: "Thoughts on Software Development"
url: "https://www.numberMumbler.com"
baseurl: ""
author: "David Janke"
fb-id: "1832411473678719"

social:
    twitter: "numberMumbler"
    # github: "numberMumbler"
    linkedin: "davidjanke"
    keybase: "numbermumbler"
    goodreads: "3192714-david"
    # instagram: "numbermumbler"


markdown: kramdown
highlishter: rouge
excerpt_separator: "<!--excerpt-->"

sass:
    sass_dir: _sass
    style: compressed

plugins:
    - jekyll-sitemap
    - jekyll-feed