title: numberMumbler
description: "Thoughts on Software Development"
baseurl: ""
author: "David Janke"

markdown: kramdown
highlishter: rouge
excerpt_separator: "<!--excerpt-->"

sass:
    sass_dir: _sass
    style: compressed

gems:
    - jekyll-sitemap